# Generated by Django 5.0.3 on 2024-03-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_investment_product_remove_investment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
