# Generated by Django 5.0.3 on 2024-03-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_investment_amount_invested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_amount',
        ),
    ]
