# Generated by Django 5.0.3 on 2024-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
