# Generated by Django 5.0.3 on 2024-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customuser_current_amount_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
    ]
